# permissions for end users to view githubissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: github-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubissue-viewer-role
rules:
- apiGroups:
  - marom.dana.io.dana.io
  resources:
  - githubissues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - marom.dana.io.dana.io
  resources:
  - githubissues/status
  verbs:
  - get
